name: flutter_segment_display_example
description: Segment display example
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  segment_display:
    path: ../

dev_dependencies:
  lint: ^1.3.0

flutter:
  uses-material-design: true
